---
- name: "EC2 Creation Playbook"
  hosts: localhost
  vars_files: 
    - key.vars
    - main.vars
  tasks:

    - name: "Creating Key..............."
      amazon.aws.ec2_key:
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        region: "{{region}}"
        name: ansible
        state: present
      register: key

    - name: " Copy key to Home directory"
      when: key.changed
      copy:
        content: "{{key.key.private_key}}"
        dest: ansible.pem
        mode: 0400

    - name: "Creating Security groups"
      amazon.aws.ec2_security_group:
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        name: Ansible
        description: SG with access to 80,443 and 22
        region: "{{region}}"
        state: present
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
          - proto: tcp
            ports:
            - 443
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 443
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
      register: sg
