---
- name: "EC2 Creation Playbook"
  hosts: localhost
  vars_files: 
    - key.vars
    - main.vars
  tasks:

    - name: "Creating Key..............."
      amazon.aws.ec2_key:
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        region: "{{region}}"
        name: ansible
        state: present
      register: key
