---
- name: "EC2 Creation Playbook"
  hosts: localhost
  vars_files: 
    - key.vars
    - main.vars
  tasks:

    - name: "Creating Key..............."
      amazon.aws.ec2_key:
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        region: "{{region}}"
        name: ansible
        state: present
      register: key

    - name: " Copy key to Home directory"
      when: key.changed
      copy:
        content: "{{key.key.private_key}}"
        dest: ansible.pem
        mode: 0400
